INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, BOOKED) VALUES ('Piccadilly', 'P1', '1Q', false);
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, BOOKED) VALUES ('Piccadilly', 'P2', '1Q', false);
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, BOOKED) VALUES ('Manhattan', 'P3', '1Q', false);
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO, BOOKED) VALUES ('Manhattan', 'P4', '2D', false);

INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Adams', 'Roy', 'radams1v@xinhuanet.com', 'United States', '2872 Marquette Street', 'NY', '1-(235)314-9823');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Adams', 'Martin', 'madams2b@msu.edu', 'China', '4 Mandrake Plaza', '', '9-(401)660-9813');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Alvarez', 'Roger', 'ralvarezk@blogs.com', 'United States', '3 Green Plaza', 'FL', '6-(980)036-6105');